2023-08-05 16:01:22,741 - WARNING - Connection pool is full, discarding connection: localhost. Connection pool size: 1
2023-08-05 16:01:22,743 - ERROR - An error occurred while scheduling the task: Message: invalid session id
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00007FF6837E4A62+57106]
	(No symbol) [0x00007FF68375CF52]
	(No symbol) [0x00007FF68362E17D]
	(No symbol) [0x00007FF68365CA69]
	(No symbol) [0x00007FF68365E064]
	GetHandleVerifier [0x00007FF683A94222+2873042]
	GetHandleVerifier [0x00007FF683AE6590+3209792]
	GetHandleVerifier [0x00007FF683ADF3AF+3180639]
	GetHandleVerifier [0x00007FF683875F25+652245]
	(No symbol) [0x00007FF683768618]
	(No symbol) [0x00007FF6837647C4]
	(No symbol) [0x00007FF6837648BC]
	(No symbol) [0x00007FF683754C33]
	BaseThreadInitThunk [0x00007FF8F6CC26AD+29]
	RtlUserThreadStart [0x00007FF8F8B8AA68+40]
Traceback (most recent call last):
  File "c:\Users\tyler\Desktop\Projects And More\Projects\Python\Library Scheduler\scheduler.py", line 53, in schedule_Task
    self.mainBrowser.book_room(username, password, ucfID, date, room_number, start_time, duration)
  File "c:\Users\tyler\Desktop\Projects And More\Projects\Python\Library Scheduler\scraperModule.py", line 150, in book_room
    self.date_change(date)
  File "c:\Users\tyler\Desktop\Projects And More\Projects\Python\Library Scheduler\scraperModule.py", line 102, in date_change
    date_button = self.safe_find_element_by_xpath('//*[@id="eq-time-grid"]/div[1]/div[1]/button[1]')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tyler\Desktop\Projects And More\Projects\Python\Library Scheduler\scraperModule.py", line 82, in safe_find_element_by_xpath
    return self.driver.find_element(By.XPATH, xpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 740, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\tyler\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00007FF6837E4A62+57106]
	(No symbol) [0x00007FF68375CF52]
	(No symbol) [0x00007FF68362E17D]
	(No symbol) [0x00007FF68365CA69]
	(No symbol) [0x00007FF68365E064]
	GetHandleVerifier [0x00007FF683A94222+2873042]
	GetHandleVerifier [0x00007FF683AE6590+3209792]
	GetHandleVerifier [0x00007FF683ADF3AF+3180639]
	GetHandleVerifier [0x00007FF683875F25+652245]
	(No symbol) [0x00007FF683768618]
	(No symbol) [0x00007FF6837647C4]
	(No symbol) [0x00007FF6837648BC]
	(No symbol) [0x00007FF683754C33]
	BaseThreadInitThunk [0x00007FF8F6CC26AD+29]
	RtlUserThreadStart [0x00007FF8F8B8AA68+40]

2023-08-05 16:01:24,765 - INFO - Server Shutdown
